package it.workfy.commons.words.bag;

import java.util.Date;
import java.util.Map;
import org.junit.Assert;
import org.junit.Test;

/**
 *
 * @author julio
 */
public class BaggerTest {

    public BaggerTest() {
    }

    @Test
    public void testGetBagOfWords() {
        final Bagger bagger = new Bagger();
        final Map<String , Integer> bagOfWords = bagger.getBagOfWords( sample() );

        bagOfWords.keySet().forEach( key -> System.out.println( key + " : " + bagOfWords.get( key ) ) );

        bagOfWords.keySet().stream().forEach( word -> {
            Assert.assertFalse( StopWordsUtil.STOP_WORDS.contains( word ) );
            Assert.assertFalse( word.contains( Normalizer.DOT ) );

            if ( word.contains( "\"" ) ) {
                System.out.println( word.replace( "\"" , "-" ) );
            }
        } );

    }

    @Test
    public void testSpeedGetBagOfWords() {
        final Bagger bagger = new Bagger();
        Date start = new Date();
        bagger.getBagOfWords( sample() );
        Date end = new Date();
        double seconds = ( end.getTime() - start.getTime() ) / 1000;
        System.out.println( "BOW process took " + seconds + " seconds." );
    }

    private String sample() {
        return "A Holanda tem uma forte política anti-bullying: desde 2015 as  escolas primárias e secundárias são "
                + "obrigadas por lei a combater os casos de bullying."
                + "Nas escolas primárias, crianças são ensinadas desde os 4 anos a fazerem um sinal de \"pare\" com "
                + "as mãos quando não gostam de uma situação ou quando acham que algum colega ultrapassou algum limite."
                + " Além disso, são estimuladas a logo conversar com um adulto sobre a situação."
                + "Em 2016, o número de crianças que alegaram ter sofrido bullying na educação primária caiu para 10% – "
                + "comparado a 14% em 2014. Nas escolas secundárias caiu de 11% em 2014 para 8% em 2016, segundo o"
                + " Ministério da Educação."
                + "“Aqui ninguém implica com ninguém. A gente respeita as diferenças e até rimos delas. Acho que isso "
                + "é reflexo da educação que recebemos nas escolas e em casa desde muito 'cedo', diz Faye, de 14 anos, "
                + "aluna de uma escola secundária em Amsterdã. 01/02/2018 120.125.00-00 88 "
                + "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa mi, hendrerit eget tristique dignissim, accumsan ut metus. Ut quis libero felis. Aliquam porttitor ipsum mi, nec euismod odio molestie consequat. Proin maximus, lacus quis imperdiet lobortis, felis neque faucibus nisi, et iaculis sem magna in massa. Sed nec placerat magna. In eget tortor egestas, laoreet ipsum ultrices, dictum tortor. Suspendisse suscipit id arcu sed congue. Cras vestibulum porta leo ut porttitor. Aenean quis nunc leo."
                + "Praesent id sagittis sem. Suspendisse vitae nibh varius, malesuada risus vitae, mollis lacus. Integer sem lorem, iaculis eu ornare quis, commodo quis turpis. Aliquam ullamcorper pretium libero, ac euismod orci vehicula ut. Duis bibendum est accumsan nunc imperdiet, sit amet porttitor urna dictum. Mauris eu velit at neque laoreet egestas. Morbi nec tincidunt justo, et facilisis nibh. Donec lorem massa, hendrerit ut aliquet non, blandit sed arcu."
                + "Maecenas laoreet viverra facilisis. Quisque accumsan dolor nisi, sit amet accumsan tellus convallis quis. Sed in diam vitae tortor ultricies tempor. Maecenas nulla mi, sodales ac magna et, euismod varius diam. Ut congue eleifend ipsum posuere auctor. Cras maximus risus eu leo tempus, eu eleifend ipsum dictum. Vestibulum vitae sodales ex."
                + "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent non diam hendrerit, porttitor quam et, aliquet libero. Nulla lacus erat, eleifend a ullamcorper sagittis, auctor sed ex. Vivamus eu pretium neque, eu scelerisque sem. Sed sit amet pharetra risus. Donec sodales a arcu eu rhoncus. Proin eu dolor nulla. Cras vel nibh facilisis, dictum neque a, feugiat justo. Praesent non mi a quam rutrum aliquet. Curabitur sodales lacus nulla, eget lacinia tortor luctus eget. Fusce mi lacus, commodo quis lorem non, ultrices convallis tellus. Quisque nunc justo, feugiat at tristique rutrum, efficitur eu urna. Nunc dapibus egestas bibendum. Vestibulum feugiat metus nunc, eget ornare justo vulputate sed."
                + "Sed elementum, tortor ut posuere scelerisque, justo arcu lacinia orci, in porttitor lorem sapien non libero. Phasellus et mauris eget nisl mollis accumsan. In mattis nisl sem, vitae ultrices nisl dictum ut. Morbi vitae euismod lectus. Duis non pretium mi. Donec id aliquet ligula. Nam a velit rhoncus elit convallis pharetra non at mauris. Quisque a tincidunt lorem. Ut luctus quis risus id tempor."
                + "Mauris eu aliquam risus, ac interdum quam. Nulla non diam neque. Cras efficitur purus hendrerit purus facilisis, id suscipit eros congue. Donec mattis dolor non nulla fermentum, rhoncus elementum nunc pretium. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras tempor quis libero at fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed egestas, enim ac scelerisque tempus, est ligula molestie lacus, ac laoreet tortor dui vitae ante. Maecenas eget ipsum laoreet, imperdiet tortor sed, porttitor tortor. Quisque quis condimentum enim, sit amet ultricies enim."
                + "Praesent egestas vestibulum mauris non hendrerit. Mauris nibh nibh, euismod dapibus enim eget, hendrerit finibus justo. Nam eu viverra libero. Praesent accumsan velit dui, nec interdum odio rutrum ac. Suspendisse efficitur laoreet tortor, dignissim posuere risus. Nulla facilisi. Aenean eu dolor non arcu sollicitudin rutrum efficitur at felis. Duis et felis eget nibh lobortis tempor. Aenean et ipsum hendrerit, ultricies risus sit amet, fermentum dolor."
                + "Vestibulum venenatis diam blandit metus faucibus gravida. Suspendisse viverra, nibh ut consectetur sollicitudin, metus metus rhoncus justo, at aliquet lacus lacus id felis. Cras ac ornare urna. Sed vehicula sit amet risus sed aliquet. Nullam est lacus, placerat at enim eu, ornare sodales mi. Morbi convallis sem eget accumsan iaculis. Mauris convallis arcu lacus, sit amet tincidunt nisl maximus non. Duis nec augue quis eros tincidunt blandit vitae quis leo. Quisque molestie lectus quis felis commodo, non tristique mauris sagittis. Pellentesque orci neque, sagittis et sem eu, feugiat aliquam augue. Nulla vel mi est. Donec eu viverra leo, sit amet sollicitudin tellus. Fusce suscipit ut purus eu tincidunt. Mauris non dolor sit amet eros hendrerit tempus. Nulla at massa eget purus vulputate varius eu eget velit."
                + "Ut congue sagittis elit, sed ornare magna laoreet suscipit. Suspendisse potenti. Nam eu justo nulla. Curabitur convallis eros non eros malesuada elementum. Duis mattis condimentum tempus. Nulla eros dui, vehicula eget sapien at, hendrerit dignissim urna. In tincidunt sapien in mattis bibendum. Sed scelerisque gravida odio, sit amet hendrerit sem gravida vel. Donec imperdiet nulla quam, a semper purus ullamcorper in. Sed at rhoncus felis. Nam non convallis sem, in pellentesque mi. Vivamus mollis purus eget leo consequat tempor. Aenean lobortis convallis massa eget accumsan. In iaculis, arcu imperdiet finibus sollicitudin, diam tellus commodo neque, a sagittis mauris dui quis est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce pulvinar enim pellentesque, gravida justo nec, commodo libero."
                + "Suspendisse facilisis erat eget dui venenatis, sit amet suscipit enim euismod. Mauris scelerisque tincidunt nibh in fringilla. Praesent congue facilisis ante et dapibus. Praesent a ex interdum, dictum velit sed, iaculis magna. Nulla elementum, leo suscipit venenatis tincidunt, magna massa iaculis metus, vitae aliquam massa velit non enim. Donec eget erat ligula. Morbi congue dui augue, et interdum tellus elementum at. Nam nulla felis, pretium vel euismod porttitor, eleifend accumsan dolor. Aliquam non eros eget odio imperdiet viverra ac scelerisque elit. Quisque at maximus tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce sit amet luctus quam. Interdum et malesuada fames ac ante ipsum primis in faucibus."
                + "Vivamus eget est vitae sapien consequat vestibulum sed non odio. Pellentesque egestas finibus posuere. Curabitur sed ante ac nulla malesuada dapibus at ac tortor. Nulla euismod erat at ligula luctus varius. Phasellus eget tempor quam, ac pretium arcu. Donec non ante eu ex faucibus consectetur vitae finibus nunc. Fusce dictum lacus leo, ut posuere ante lobortis sed. Ut enim leo, volutpat vel nibh eget, bibendum scelerisque dolor. Vestibulum vitae cursus tellus."
                + "Mauris nunc purus, scelerisque non vehicula gravida, faucibus vel sapien. Morbi auctor nunc porta nunc fermentum viverra vel at justo. Pellentesque sollicitudin, erat id imperdiet imperdiet, augue augue consectetur metus, id sodales nisi velit vel lectus. Integer placerat molestie sodales. Curabitur convallis dolor tortor, quis iaculis enim iaculis non. Maecenas id luctus nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam in nulla non lectus interdum malesuada. Vestibulum eu leo lobortis, condimentum metus vitae, imperdiet velit."
                + "Donec vel tristique dui. Vestibulum vestibulum tempus diam vitae tincidunt. Fusce et nunc eu mi vestibulum semper. Cras ullamcorper urna et purus tincidunt convallis. Integer varius at enim vel bibendum. Proin iaculis vel nibh ac euismod. Vivamus malesuada nulla et nisl volutpat iaculis ut sed lorem."
                + "Aenean dictum scelerisque felis ut auctor. Quisque sit amet lacinia nibh. Praesent a eros metus. Pellentesque vitae placerat ligula, id sagittis tellus. Fusce egestas suscipit condimentum. Aliquam at augue ultrices, ornare odio vel, tristique elit. Donec aliquet tempus lorem, in gravida ante tempor sit amet."
                + "Mauris velit nisi, lobortis vel fermentum a, tempus sit amet elit. Proin orci eros, finibus vel lacinia id, ullamcorper eget justo. Pellentesque ac sapien eget erat imperdiet vestibulum. Nullam vehicula leo quis nunc commodo, eu semper nisi egestas. Phasellus feugiat quis arcu nec ullamcorper. Sed faucibus non justo sed accumsan. Mauris quis ultricies neque, et vestibulum neque. In nec laoreet tellus, eget sodales elit."
                + "Praesent vitae nisi sollicitudin, lacinia arcu sed, hendrerit turpis. In condimentum justo nulla, vitae aliquam diam dictum ac. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec vehicula elit diam, at aliquam dui eleifend sit amet. Etiam eu ullamcorper erat. Maecenas ex augue, vehicula sed ex eu, maximus interdum mauris. Nunc eget sapien nec purus suscipit mollis pulvinar sed augue. Sed tincidunt purus nec porta lobortis. Fusce eleifend scelerisque justo vitae bibendum. Proin accumsan eleifend tortor id hendrerit. Vivamus dapibus ligula enim, eget vulputate urna vulputate bibendum. Aenean et blandit nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
                + "Nulla et tristique erat. Donec ut lorem egestas lorem maximus egestas. Duis aliquet luctus lectus, id aliquet nulla tincidunt ac. Vestibulum faucibus lectus ante, vitae maximus nisi tempus sed. Morbi a tortor mollis turpis pellentesque mollis. Morbi et lorem pretium, placerat sem quis, euismod elit. Nam vel aliquam nisi, ac aliquet libero. Morbi molestie, arcu in consectetur ultricies, turpis nulla sodales tortor, nec malesuada lacus sapien id tellus. Vestibulum pellentesque, risus at faucibus varius, sem elit fermentum ex, non eleifend augue diam sed magna. Sed laoreet pellentesque libero, id faucibus urna facilisis sit amet. Duis sodales dui egestas posuere vehicula. Quisque placerat, dolor in aliquet tincidunt, sem quam fermentum metus, vel rutrum lacus eros in dui. Fusce varius nulla ut nulla sagittis viverra. Sed commodo purus ac tempor semper. Nulla eu lectus pharetra ipsum finibus feugiat sodales a libero."
                + "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla facilisi. Fusce sollicitudin finibus sapien eu imperdiet. Integer ac fringilla massa. Vivamus maximus elit vitae ornare cursus. Donec feugiat, arcu pretium aliquam volutpat, tortor ante commodo quam, ut accumsan purus orci sit amet lorem. Donec erat augue, faucibus sed est et, pretium congue purus. Maecenas aliquam, ante at vestibulum aliquet, magna nisi malesuada ligula, ac vulputate nulla ligula id metus. Pellentesque elementum lobortis ligula, eu ornare sapien aliquet sed. Nam hendrerit at erat vitae mattis. Morbi sagittis congue orci id accumsan. Nam porttitor mollis nisi, ut eleifend tellus aliquet ac. Mauris vel nulla id metus fermentum tincidunt nec ut purus."
                + "Nunc commodo ante justo, nec semper tortor aliquet in. Mauris varius dolor ac eros sollicitudin consectetur. Duis libero dolor, venenatis finibus nunc ac, venenatis laoreet tortor. Curabitur in interdum augue, id rutrum dolor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eu egestas orci. Fusce facilisis accumsan vestibulum. Cras ultricies venenatis mauris. Donec tempus felis non dolor blandit, at pretium felis ornare. Quisque venenatis lacus odio, nec suscipit justo hendrerit ut. Ut vel rhoncus justo, id tristique sapien."
                + "Ut sodales justo purus, a dictum turpis pharetra non. Curabitur viverra dictum erat sed vestibulum. Morbi elementum, neque ac mattis porttitor, leo elit cursus ante, ac placerat ante ante a sapien. Morbi finibus, neque quis pretium placerat, massa mauris tincidunt metus, in rutrum tellus ligula vel nibh. In nibh lectus, vulputate a lorem non, dictum tincidunt tortor. Donec luctus metus risus, vitae accumsan sem viverra in. Nullam eu est eros. Nulla egestas blandit urna non maximus. Donec eu finibus tortor, sed suscipit dui. Phasellus ut ullamcorper nulla. Aliquam hendrerit urna ac metus mollis cursus vitae eu mauris. Vestibulum id mi ipsum. Vestibulum dolor enim, venenatis ac neque ac, tincidunt fermentum turpis."
                + "Ut aliquam, nisl eget tristique dignissim, ipsum nibh venenatis metus, nec fermentum augue arcu sed tortor. Aenean feugiat, est quis convallis maximus, risus tortor sollicitudin risus, et posuere arcu est et quam. Vestibulum scelerisque ornare dolor, ac sodales diam dapibus vel. Aenean ultricies iaculis nibh, in dignissim odio varius a. Vestibulum placerat erat quis sem molestie posuere. Suspendisse auctor purus quam, at vehicula diam sodales in. In dapibus congue mi, eget hendrerit urna aliquam vel. Nunc molestie pharetra elit vel venenatis. Integer sed nibh sit amet arcu varius fermentum. Aenean porttitor orci id neque mattis, at imperdiet quam volutpat. Quisque eu odio euismod, suscipit quam eget, posuere lectus. Sed auctor sem sed laoreet viverra. Sed elementum, dui quis pharetra eleifend, sapien tortor facilisis ante, id pretium nunc neque rutrum nulla."
                + "Vestibulum varius felis eget vehicula suscipit. Ut consequat tellus et dapibus sollicitudin. Praesent porta ante a urna suscipit dignissim. Sed ut felis ut purus vehicula porta. Suspendisse potenti. Nullam pharetra ex a consequat sagittis. Aenean luctus leo a magna iaculis, a vestibulum ante maximus. In id accumsan enim, nec maximus eros. Pellentesque at ornare erat, a mattis nulla. Integer molestie, est sed vehicula dignissim, felis quam consectetur enim, non fermentum nisi enim non turpis. Suspendisse blandit porta neque, eu vulputate sem malesuada quis. Donec vitae ultricies quam. Suspendisse bibendum mauris quis mi mollis sollicitudin. Etiam ac urna et nunc cursus rutrum sed sit amet quam. Donec tristique aliquet nibh, in maximus risus. Curabitur mauris eros, pulvinar non dolor eget, faucibus dapibus eros. Cras placerat tellus non vulputate";
    }
}
